# .github/workflows/draft-pdf.yml
name: Draft PDF

on:
  push:
    # Only rebuild when paper-related files change (adjust to your layout)
    paths:
      - paper.md
      - paper.bib
      - assets/**
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    name: Paper Draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss        # or 'jose'
          paper-path: paper.md # relative to repo root

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf      # matches the output produced by the action
