# .github/workflows/draft-pdf.yml
name: Draft PDF

on:
  push:
    paths:
      - paper/**
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    name: Paper Draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss               # or 'jose'
          paper-path: paper/paper.md  # <-- point to your file in paper/

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf       # <-- output lives next to input
